export const mockListings = [
  {
    id: 1,
    brand: 'Nike',
    model: 'Air Max 90',
    size: 10.0,
    condition: 'Like New',
    price: 120.00,
    description: 'Barely worn, clean pair. No box.',
    image_url: '/listings/air-max-90.svg',
    seller_username: 'sneakerhead1',
    seller_id: 1,
    seller_total_listings: 8,
    seller_created_at: '2024-11-03T12:00:00.000Z',
    seller_auth_provider: 'google',
    seller_oauth_email_verified: true,
    seller_avg_rating: '4.80',
    seller_review_count: 24,
    seller_mutual_connection_count: 3,
    seller_mutual_connections: [
      { id: 1, connection_label: 'Jordan23', connection_handle: 'Jordan23', relationship_context: 'previous_buyer' },
      { id: 2, connection_label: 'KickzKing', connection_handle: 'KickzKing', relationship_context: 'previous_buyer' },
      { id: 3, connection_label: 'SoleSeeker', connection_handle: 'SoleSeeker', relationship_context: 'previous_buyer' },
    ],
    seller_social_verification: {
      id: 1,
      platform: 'Instagram',
      profile_url: 'https://instagram.com/sneakerhead1',
      username: 'sneakerhead1',
      status: 'verified',
      verified_at: '2026-04-20T12:00:00.000Z',
    },
  },
  {
    id: 2,
    brand: 'Jordan',
    model: 'Air Jordan 1 Retro High OG',
    size: 9.5,
    condition: 'Good',
    price: 180.00,
    description: 'Some creasing on the toe box, overall still clean.',
    image_url: '/listings/air-jordan-1-retro-high-og.svg',
    seller_username: 'sneakerhead1',
    seller_id: 1,
    seller_total_listings: 8,
    seller_created_at: '2024-11-03T12:00:00.000Z',
    seller_auth_provider: 'google',
    seller_oauth_email_verified: true,
    seller_avg_rating: '4.80',
    seller_review_count: 24,
    seller_mutual_connection_count: 3,
    seller_mutual_connections: [
      { id: 1, connection_label: 'Jordan23', connection_handle: 'Jordan23', relationship_context: 'previous_buyer' },
      { id: 2, connection_label: 'KickzKing', connection_handle: 'KickzKing', relationship_context: 'previous_buyer' },
      { id: 3, connection_label: 'SoleSeeker', connection_handle: 'SoleSeeker', relationship_context: 'previous_buyer' },
    ],
    seller_social_verification: {
      id: 1,
      platform: 'Instagram',
      profile_url: 'https://instagram.com/sneakerhead1',
      username: 'sneakerhead1',
      status: 'verified',
      verified_at: '2026-04-20T12:00:00.000Z',
    },
  },
  {
    id: 3,
    brand: 'Adidas',
    model: 'Yeezy Boost 350 V2',
    size: 11.0,
    condition: 'New',
    price: 320.00,
    description: 'Brand new in box, never worn.',
    image_url: '/listings/yeezy-boost-350-v2.svg',
    seller_username: 'kickseller',
    seller_id: 2,
    seller_total_listings: 15,
    seller_created_at: '2026-04-14T12:00:00.000Z',
    seller_auth_provider: 'google',
    seller_oauth_email_verified: true,
    seller_avg_rating: '4.60',
    seller_review_count: 41,
    seller_mutual_connection_count: 1,
    seller_mutual_connections: [
      { id: 4, connection_label: 'RetroRunner', connection_handle: 'RetroRunner', relationship_context: 'previous_buyer' },
    ],
    seller_social_verification: {
      id: 2,
      platform: 'TikTok',
      profile_url: 'https://tiktok.com/@kickseller',
      username: 'kickseller',
      status: 'submitted',
      verified_at: null,
    },
  },
  {
    id: 4,
    brand: 'New Balance',
    model: '990v5',
    size: 10.5,
    condition: 'Fair',
    price: 75.00,
    description: 'Well worn but still very solid. Great beater.',
    image_url: '/listings/new-balance-990v5.svg',
    seller_username: 'kickseller',
    seller_id: 2,
    seller_total_listings: 15,
    seller_created_at: '2026-04-14T12:00:00.000Z',
    seller_auth_provider: 'google',
    seller_oauth_email_verified: true,
    seller_avg_rating: '4.60',
    seller_review_count: 41,
    seller_mutual_connection_count: 1,
    seller_mutual_connections: [
      { id: 4, connection_label: 'RetroRunner', connection_handle: 'RetroRunner', relationship_context: 'previous_buyer' },
    ],
    seller_social_verification: {
      id: 2,
      platform: 'TikTok',
      profile_url: 'https://tiktok.com/@kickseller',
      username: 'kickseller',
      status: 'submitted',
      verified_at: null,
    },
  },
  {
    id: 5,
    brand: 'Nike',
    model: 'Dunk Low Retro',
    size: 9.0,
    condition: 'Like New',
    price: 140.00,
    description: 'Worn twice only, like brand new.',
    image_url: '/listings/dunk-low-retro.svg',
    seller_username: 'airmax_fan',
    seller_id: 3,
    seller_total_listings: 3,
    seller_created_at: '2025-10-03T12:00:00.000Z',
    seller_auth_provider: 'password',
    seller_oauth_email_verified: false,
    seller_avg_rating: '5.00',
    seller_review_count: 7,
    seller_mutual_connection_count: 0,
    seller_mutual_connections: [],
    seller_social_verification: null,
  },
];

export const mockReviews = {
  1: [
    { id: 1, reviewer_username: 'kickseller', rating: 5, comment: 'Great condition, fast shipping!', created_at: '2024-01-10', is_transaction_locked: true },
    { id: 2, reviewer_username: 'airmax_fan', rating: 4, comment: 'Exactly as described. Would buy again.', created_at: '2024-01-08', is_transaction_locked: true },
  ],
  2: [
    { id: 3, reviewer_username: 'airmax_fan', rating: 3, comment: 'Good but slight creasing not fully mentioned.', created_at: '2024-01-05', is_transaction_locked: true },
  ],
  3: [],
  4: [],
  5: [],
};

const sneakerheadSocialStimulus = {
  verifiedBy: 12,
  mutualConnections: 3,
  recentBuyers: ['Jordan23', 'KickzKing', 'SoleSeeker'],
  badges: ['Top Seller', 'Community Trusted', 'Fast Shipper'],
  responseRate: 98,
  communityRank: 'Elite',
};

const kicksellerSocialStimulus = {
  verifiedBy: 28,
  mutualConnections: 1,
  recentBuyers: ['RetroRunner', 'SneakPeak', 'HypeHunter'],
  badges: ['Verified Seller', 'Fast Shipper'],
  responseRate: 95,
  communityRank: 'Pro',
};

const airmaxFanSocialStimulus = {
  verifiedBy: 4,
  mutualConnections: 0,
  recentBuyers: ['NewKid'],
  badges: [],
  responseRate: 80,
  communityRank: 'Newcomer',
};

// Controlled social-trust stimuli keyed by seller handle. Numeric keys preserve
// compatibility with the fallback mock listings used when the API is unavailable.
export const mockSocialData = {
  sneakerhead1: sneakerheadSocialStimulus,
  kickseller: kicksellerSocialStimulus,
  airmax_fan: airmaxFanSocialStimulus,
  1: sneakerheadSocialStimulus,
  2: kicksellerSocialStimulus,
  3: airmaxFanSocialStimulus,
};
